[package]
name = "sending-many-concurrent-requests"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {workspace = true, features = ["full"]}
reqwest = {workspace = true, features = ["json"]}
futures = {workspace = true}