[package]
name = "rust-by-example-3"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["examples/*"]
resolver = "2"

[workspace.dependencies]
serde_json = "1.0.140"
serde = "1.0.219"
reqwest = "0.12.15"
tokio = "1.44.1"
futures = "0.3.31"
base64 = "0.22.1"
toml = "0.8.20"

[dependencies]
